### ISSUE TITLE
Error while loading mod on Fedora 36 Steam Flatpak

### ISSUE THREAD

**Issue by lilian-pouliquen** [tylergibbs2/StardewValleyRoguelike#1] opened 2022-09-10 21:30 UTC
Hello,
I wanted to try the mod on my Fedora 36 using Steam through Flatpak, but the mod did not work when the game started. I then looked into SMAPI's logs and saw the following error while loading StardewValleyRoguelike:

```
[game] TypeInitializationException: The type initializer for 'HarmonyLib.FileLog' threw an exception.
---> ArgumentException: Path cannot be the empty string or all whitespace. (Parameter 'path')
   at System.IO.Directory.CreateDirectory(String path)
   at HarmonyLib.FileLog..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.AccessTools.Method(Type type, String name, Type[] parameters, Type[] generics)
   at StardewRoguelike.Patch.ApplyPatch(Harmony harmonyInstance)
```

Thank you in advance for your answer.

**Comment by tylergibbs2** [comment] 2022-09-10 23:32
It seems like this is an issue with the version of Harmony that SMAPI uses. Until SMAPI updates the version of Harmony that it's bundled with, the temporary workaround is to `mkdir ~/Desktop`. It looks as though this path is required.

**Comment by lilian-pouliquen** [comment] 2022-09-11 00:36
> It seems like this is an issue with the version of Harmony that SMAPI uses. Until SMAPI updates the version of Harmony that it's bundled with, the temporary workaround is to `mkdir ~/Desktop`. It looks as though this path is required.

Thanks for the workaround. Unfortunately, although I added the `Desktop` dir to my `/home/$USER`, I still get the error.
I will wait for a SMAPI update then.

Thank you!

**Comment by tylergibbs2** [comment] 2022-09-11 00:38
Although this is a wontfix, I'll still look around for a solution. Feel free to follow the issue, I'll update here.

**Comment by tylergibbs2** [comment] 2022-09-11 01:10
Okay -- it looks like Harmony has an environment variable you can use to set the location of its log file. The true root of the issue is that Harmony has troubles with knowing where to put log files on MacOS/Linux.

Try setting the `HARMONY_LOG_FILE` environment variable and run with that. It could be any directory.

**Comment by lilian-pouliquen** [comment] 2022-09-11 12:28
> Okay -- it looks like Harmony has an environment variable you can use to set the location of its log file. The true root of the issue is that Harmony has troubles with knowing where to put log files on MacOS/Linux.
> 
> Try setting the `HARMONY_LOG_FILE` environment variable and run with that. It could be any directory.
> 
> [ref](https://github.com/pardeike/Harmony/issues/442#issuecomment-1000275970)

Okay, I confirm that it is working for me! thank you again for your investigations!

**Closed** 2022-09-11 16:57 UTC
Labels: wontfix
